baseurl: https://moodlebox.net/
title: MoodleBox
theme:
  - hugo-video
  - hugo-notice
  - hugo-cloak-email

# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage: en

# Site time zone
timeZone: Europe/Zurich

# Renders the default content language in subdir, e.g. /en/. The root directory / will redirect to /en/
defaultContentLanguageInSubdir: true

# Show a placeholder instead of the default value or an empty string if a translation is missing
# enableMissingTranslationPlaceholders: false

# Log File path (if set, logging enabled automatically)
# logFile: "./hugolog.txt"

# Define the number of posts per page
paginate: 5

# Allow taxonomy term with special characters
preserveTaxonomyNames: true

# Enable robots.txt generation
enableRobotsTXT: true

# Disable taxonomy pages
# disableKinds:
#   - taxonomy
#   - taxonomyTerm

# Disable incomplete languages
#disableLanguages: [ "de" ]

menu:
  topbar:
  - name: GitHub
    pre: <i class='fa fa-2x fa-github'></i>
    url: https://github.com/moodlebox
    weight: 1
#  - name: Facebook
#    pre: <i class='fa fa-2x fa-facebook'></i>
#    url: https://facebook.com
#    weight: 2
  - name: Twitter
    pre: <i class='fa fa-2x fa-twitter'></i>
    url: https://twitter.com/moodlebox
    weight: 3
  - name: Mastodon
    pre: <i class='fa fa-2x fa-mastodon'></i>
    url: https://openedtech.social/@moodlebox
    weight: 3
  - name: Mail
    pre: <i class='fa fa-2x fa-envelope'></i>
    url: mailto:nicolas@martignoni.net
    weight: 4

params:
  author: Nicolas Martignoni
  address: ''
  defaultSlogan: A Moodle platform on Raspberry Pi
  defaultDescription: MoodleBox is a standalone small and cheap mobile device working without Internet. It combines a wireless access point with a full featured Moodle server.
  defaultKeywords:
  - MoodleBox
  - Moodle
  - Moodle Box
  - Moodle in a Box
  - Moodle Raspberry
  - Moodle Raspberry Pi
  - Moodle Pi
  - Moodle RPi
  - PirateBox
  - Pirate Box
  - BiblioBox
  - Biblio Box
  - Raspberry
  - Raspberry Pi
  - RPi
  - Pi
  - Classroom
  - Wi-Fi
  - WiFi
  - Box

  # Since this template is static, the contact form uses www.formspree.io as a
  # proxy. The form makes a POST request to their servers to send the actual
  # email. Visitors can send up to a 1000 emails each month for free.
  #
  # What you need to do for the setup?
  #
  # - set your email address under 'email' below
  # - upload the generated site to your server
  # - send a dummy email yourself to confirm your account
  # - click the confirm link in the email from www.formspree.io
  # - you're done. Happy mailing!
  #
  # Enable the contact form by entering your Formspree.io email
  email: nicolas@martignoni.net

  logo: img/logo.png

  social:
    twitter: moodlebox
    mastodon: https://openedtech.social/@moodlebox
    github: moodlebox

  typeseo:
    - app

  app:
    price: "0"
    currency: "EUR"
    category: "EducationalApplication"
    device: "Raspberry Pi"
    os: "Raspberry OS"

  carousel:
    enable: true

  news:
    enable: true

  features:
    enable: true

  recent_posts:
    enable: true
    subtitle: ''
    title: ''

  see_more:
    enable: false
    icon: fa fa-file-code-o
    link_text: Check other homepages
    link_url: '#'
    subtitle: We have prepared for you more than 40 different HTML pages, including
      5 variations of homepage.
    title: Do you want to see more?

  topbar:
    enable: false
    text: ""

#  viewMorePostLink: /help/

  widgets:
    categories: false
    search: true
    tags: false
    related: true
    recentnews: true

  # Enable/disable post-footer links
  privacy:
    enable: true
  cookies:
    enable: false
  license:
    enable: true
  donate:
    enable: true

  # Enable Matomo analytics by entering your tracking code
  matomoAnalytics:
    siteid: 2
    matomoroot: "stats.martignoni.net" # Do not add slashes

related:
  threshold: 50
  includeNewer: true
  toLower: true
  indices:
    - name: "keywords"
      weight: 200

    - name: "categories"
      weight: 100

    - name: "tags"
      weight: 50

    - name: "date"
      weight: 1
      pattern: "2006"

privacy:
  youtube:
    privacyEnhanced: true

# pygmentsCodeFences: true
# pygmentsCodeFencesGuessSyntax: true
# pygmentsUseClasses: true
# pygmentsStyle: "emacs"

markup:
  goldmark:
    parser:
      attribute:
        block: true
        title: true
    renderer:
      unsafe: true
  highlight:
    style: emacs
    lineNumbersInTable: true
    noClasses: true

imaging:
  anchor: Smart
  bgColor: '#ffffff'
  hint: drawing
  quality: 90
  resampleFilter: Lanczos

#outputFormats:
#  JS:
#    mediaType: application/javascript
#    baseName: 'search '
#    path: 'js'
#    isPlainText: true

outputs:
#  home: ["HTML", "JSON", "RSS", "JS"]
  home: ["HTML", "JSON", "RSS"]
  page: ["HTML"]

permalinks:
  help: /help/:slug
  # kb: /kb/:slug
  # blog: "/blog/:year/:month/:day/:filename/"

minify:
  disableJS: true
