mounts:
  # Content mounts, fills in the gaps in other languages content with 'en' content
  # 'fr' content
  - source: content/fr
    target: content
    sites:
      matrix:
        languages:
          - fr
  # 'de' content
  - source: content/de
    target: content
    sites:
      matrix:
        languages:
          - de
  # 'es' content
  - source: content/es
    target: content
    sites:
      matrix:
        languages:
          - es
  # 'en' content (default content)
  - source: content/en
    target: content
    sites:
      matrix:
        languages:
          - '*'

  # This adds hugo_stats.json to Hugo's server watcher, for PurgeCSS
  - source: assets
    target: assets

  - source: hugo_stats.json
    target: assets/watching/hugo_stats.json
